FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY index.html ./
COPY public ./public
COPY src ./src
COPY vite.config.js ./

ARG VITE_APP_BASE_URL="https://runsee.runnsee.net"
ARG VITE_API_BASE_URL="https://api.runnsee.net"
ARG VITE_LOCAL_API_BASE_URL="http://backend:3003"
ENV VITE_APP_BASE_URL=${VITE_APP_BASE_URL}
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_LOCAL_API_BASE_URL=${VITE_LOCAL_API_BASE_URL}

RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
