export const TABLES = [
  {
    name: "AppUser",
    model: "appUser",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["createdAt", "updatedAt"],
    columns: ["id", "displayName", "createdAt", "updatedAt"],
  },
  {
    name: "StravaConnection",
    model: "stravaConnection",
    orderBy: { connectedAt: "asc" },
    dateTimeColumns: [
      "accessTokenExpiresAt",
      "connectedAt",
      "lastTokenRefreshAt",
      "createdAt",
      "updatedAt",
    ],
    columns: [
      "id",
      "appUserId",
      "stravaAthleteId",
      "accessToken",
      "refreshToken",
      "accessTokenExpiresAt",
      "grantedScopes",
      "connectedAt",
      "lastTokenRefreshAt",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "Athlete",
    model: "athlete",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["lastFetchedAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "connectionId",
      "stravaAthleteId",
      "username",
      "firstname",
      "lastname",
      "city",
      "state",
      "country",
      "sex",
      "profileMediumUrl",
      "profileUrl",
      "rawJson",
      "lastFetchedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "Activity",
    model: "activity",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: [
      "startDate",
      "startDateLocal",
      "summaryFetchedAt",
      "detailsFetchedAt",
      "lastFetchedAt",
      "createdAt",
      "updatedAt",
    ],
    columns: [
      "id",
      "athleteId",
      "stravaActivityId",
      "resourceState",
      "externalId",
      "uploadId",
      "name",
      "description",
      "type",
      "sportType",
      "workoutType",
      "startDate",
      "startDateLocal",
      "timezone",
      "utcOffset",
      "distance",
      "movingTime",
      "elapsedTime",
      "totalElevationGain",
      "startLatlngJson",
      "endLatlngJson",
      "achievementCount",
      "kudosCount",
      "commentCount",
      "athleteCount",
      "photoCount",
      "prCount",
      "totalPhotoCount",
      "trainer",
      "commute",
      "manual",
      "private",
      "flagged",
      "averageSpeed",
      "maxSpeed",
      "averageCadence",
      "averageWatts",
      "weightedAverageWatts",
      "kilojoules",
      "deviceWatts",
      "hasHeartrate",
      "averageHeartrate",
      "maxHeartrate",
      "averageTemp",
      "sufferScore",
      "calories",
      "mapId",
      "mapSummaryPolyline",
      "mapPolyline",
      "gearId",
      "isDetailed",
      "summaryJson",
      "rawJson",
      "summaryFetchedAt",
      "detailsFetchedAt",
      "lastFetchedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "SyncJob",
    model: "syncJob",
    orderBy: { queuedAt: "asc" },
    dateTimeColumns: [
      "lastProcessedActivityDate",
      "queuedAt",
      "startedAt",
      "endedAt",
      "createdAt",
      "updatedAt",
    ],
    columns: [
      "id",
      "appUserId",
      "jobType",
      "status",
      "triggerSource",
      "message",
      "errorDetails",
      "progressPercent",
      "pagesProcessed",
      "activitiesSeen",
      "activitiesInserted",
      "activitiesUpdated",
      "activitiesFailed",
      "detailsFetched",
      "lastProcessedActivityDate",
      "lastProcessedActivityId",
      "requestedAfterEpoch",
      "resultJson",
      "queuedAt",
      "startedAt",
      "endedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "SyncCursor",
    model: "syncCursor",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["createdAt", "updatedAt"],
    columns: ["id", "appUserId", "cursorName", "cursorValue", "createdAt", "updatedAt"],
  },
];

export function createSelect(columns) {
  return Object.fromEntries(columns.map((column) => [column, true]));
}

export function getTableDefinition(tableName) {
  return TABLES.find((table) => table.name === tableName) || null;
}
