export const TABLES = [
  {
    name: "AppUser",
    model: "appUser",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["lastLoginAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "email",
      "emailNormalized",
      "passwordHash",
      "displayName",
      "role",
      "status",
      "lastLoginAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "UserSession",
    model: "userSession",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["expiresAt", "revokedAt", "lastSeenAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "appUserId",
      "tokenHash",
      "expiresAt",
      "revokedAt",
      "lastSeenAt",
      "ipAddress",
      "userAgent",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "UserStravaApp",
    model: "userStravaApp",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["createdAt", "updatedAt"],
    columns: ["id", "appUserId", "clientId", "clientSecretEncrypted", "createdAt", "updatedAt"],
  },
  {
    name: "StravaConnection",
    model: "stravaConnection",
    orderBy: { connectedAt: "asc" },
    dateTimeColumns: [
      "accessTokenExpiresAt",
      "connectedAt",
      "lastTokenRefreshAt",
      "createdAt",
      "updatedAt",
    ],
    columns: [
      "id",
      "appUserId",
      "userStravaAppId",
      "stravaAthleteId",
      "accessToken",
      "refreshToken",
      "accessTokenExpiresAt",
      "grantedScopes",
      "connectedAt",
      "lastTokenRefreshAt",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "Athlete",
    model: "athlete",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["lastFetchedAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "connectionId",
      "stravaAthleteId",
      "username",
      "firstname",
      "lastname",
      "city",
      "state",
      "country",
      "sex",
      "profileMediumUrl",
      "profileUrl",
      "rawJson",
      "lastFetchedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "Activity",
    model: "activity",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: [
      "startDate",
      "startDateLocal",
      "sourceCreatedAt",
      "sourceUpdatedAt",
      "sourceSyncedAt",
      "summaryFetchedAt",
      "detailsFetchedAt",
      "lastFetchedAt",
      "mergedAt",
      "userRpeUpdatedAt",
      "createdAt",
      "updatedAt",
    ],
    columns: [
      "id",
      "appUserId",
      "athleteId",
      "stravaActivityId",
      "sourceProvider",
      "sourceActivityId",
      "sourcePriority",
      "sourceCreatedAt",
      "sourceUpdatedAt",
      "sourceSyncedAt",
      "sourceUrl",
      "hasExternalEnrichment",
      "isMerged",
      "mergedIntoActivityId",
      "mergedAt",
      "resourceState",
      "externalId",
      "uploadId",
      "name",
      "description",
      "type",
      "sportType",
      "workoutType",
      "startDate",
      "startDateLocal",
      "timezone",
      "utcOffset",
      "distance",
      "movingTime",
      "elapsedTime",
      "totalElevationGain",
      "totalElevationLoss",
      "startLatlngJson",
      "endLatlngJson",
      "achievementCount",
      "kudosCount",
      "commentCount",
      "athleteCount",
      "photoCount",
      "prCount",
      "totalPhotoCount",
      "trainer",
      "commute",
      "manual",
      "private",
      "flagged",
      "averageSpeed",
      "maxSpeed",
      "averageCadence",
      "averageWatts",
      "weightedAverageWatts",
      "kilojoules",
      "deviceWatts",
      "hasHeartrate",
      "averageHeartrate",
      "maxHeartrate",
      "averageTemp",
      "sufferScore",
      "calories",
      "mapId",
      "mapSummaryPolyline",
      "mapPolyline",
      "gearId",
      "isDetailed",
      "summaryJson",
      "rawJson",
      "summaryFetchedAt",
      "detailsFetchedAt",
      "lastFetchedAt",
      "userRpe",
      "userRpeUpdatedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "UserTrainingAnalyticsSettings",
    model: "userTrainingAnalyticsSettings",
    orderBy: { effectiveFrom: "asc" },
    dateTimeColumns: ["effectiveFrom", "archivedAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "appUserId",
      "effectiveFrom",
      "archivedAt",
      "isActive",
      "heartRateMax",
      "restingHeartrate",
      "biologicalSex",
      "heartRateZone1Max",
      "heartRateZone2Max",
      "heartRateZone3Max",
      "heartRateZone4Max",
      "intensitySourcePriority",
      "efficiencyMinDurationMinutes",
      "efficiencyMaxElevationPerKm",
      "efficiencyExcludeTrail",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "UserRaceObjective",
    model: "userRaceObjective",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["raceDate", "archivedAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "appUserId",
      "name",
      "raceDate",
      "distanceMeters",
      "targetPaceSecondsPerKm",
      "notes",
      "isActive",
      "archivedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "UserAiAssistantConfig",
    model: "userAiAssistantConfig",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["createdAt", "updatedAt"],
    columns: [
      "id",
      "appUserId",
      "provider",
      "model",
      "apiKeyEncrypted",
      "systemPrompt",
      "enabled",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "ExternalProviderConnection",
    model: "externalProviderConnection",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: [
      "consentAcceptedAt",
      "connectedAt",
      "disconnectedAt",
      "lastSyncAt",
      "lastBackfillStartedAt",
      "lastBackfillEndedAt",
      "lastErrorAt",
      "createdAt",
      "updatedAt",
    ],
    columns: [
      "id",
      "appUserId",
      "providerCode",
      "status",
      "displayName",
      "accountIdentifier",
      "encryptedSession",
      "sessionSchemaVersion",
      "consentAcceptedAt",
      "connectedAt",
      "disconnectedAt",
      "lastSyncAt",
      "lastBackfillStartedAt",
      "lastBackfillEndedAt",
      "lastErrorCode",
      "lastErrorMessage",
      "lastErrorAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "ExternalProviderRawData",
    model: "externalProviderRawData",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["syncedAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "appUserId",
      "providerCode",
      "dataType",
      "providerDateKey",
      "providerResourceId",
      "payloadJson",
      "payloadHash",
      "status",
      "syncedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "ExternalDailyRecoverySnapshot",
    model: "externalDailyRecoverySnapshot",
    orderBy: { snapshotDate: "asc" },
    dateTimeColumns: ["snapshotDate", "syncedAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "appUserId",
      "sourceProvider",
      "snapshotDate",
      "timezone",
      "sleepDurationSeconds",
      "sleepScore",
      "hrvAvgMs",
      "hrvStatus",
      "restingHr",
      "stressAvg",
      "stressMax",
      "bodyBatteryMorning",
      "bodyBatteryMin",
      "bodyBatteryMax",
      "bodyBatteryEnd",
      "trainingReadinessScore",
      "trainingReadinessStatus",
      "dataQuality",
      "syncedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "ActivityProviderEnrichment",
    model: "activityProviderEnrichment",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["matchedAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "appUserId",
      "activityId",
      "providerCode",
      "providerActivityId",
      "matchConfidence",
      "matchedAt",
      "status",
      "normalizedJson",
      "rawDataId",
      "lastErrorCode",
      "lastErrorMessage",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "ActivityProviderLink",
    model: "activityProviderLink",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["matchedAt", "createdAt", "updatedAt"],
    columns: [
      "id",
      "appUserId",
      "activityId",
      "provider",
      "providerActivityId",
      "matchStatus",
      "matchConfidence",
      "matchedAt",
      "rawDataId",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "ProviderBackfillCursor",
    model: "providerBackfillCursor",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: [
      "nextWindowEndDate",
      "oldestFetchedDate",
      "lastRunAt",
      "lastSuccessAt",
      "createdAt",
      "updatedAt",
    ],
    columns: [
      "id",
      "appUserId",
      "provider",
      "resourceType",
      "status",
      "nextWindowEndDate",
      "oldestFetchedDate",
      "windowDays",
      "lastRunAt",
      "lastSuccessAt",
      "lastErrorCode",
      "lastErrorMessage",
      "totalWindowsProcessed",
      "totalActivitiesImported",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "ProviderBackfillWindowLog",
    model: "providerBackfillWindowLog",
    orderBy: { startedAt: "asc" },
    dateTimeColumns: [
      "windowStartDate",
      "windowEndDate",
      "startedAt",
      "endedAt",
      "createdAt",
      "updatedAt",
    ],
    columns: [
      "id",
      "cursorId",
      "appUserId",
      "provider",
      "resourceType",
      "windowStartDate",
      "windowEndDate",
      "status",
      "fetchedCount",
      "rawUpsertedCount",
      "matchedCount",
      "garminOnlyCreatedCount",
      "garminOnlyUpdatedCount",
      "ambiguousCount",
      "rejectedCount",
      "duplicateCountAfterWindow",
      "resultJson",
      "startedAt",
      "endedAt",
      "errorCode",
      "errorMessage",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "SyncJob",
    model: "syncJob",
    orderBy: { queuedAt: "asc" },
    dateTimeColumns: [
      "lastProcessedActivityDate",
      "queuedAt",
      "startedAt",
      "endedAt",
      "createdAt",
      "updatedAt",
    ],
    columns: [
      "id",
      "appUserId",
      "jobType",
      "status",
      "triggerSource",
      "message",
      "errorDetails",
      "progressPercent",
      "pagesProcessed",
      "activitiesSeen",
      "activitiesInserted",
      "activitiesUpdated",
      "activitiesFailed",
      "detailsFetched",
      "lastProcessedActivityDate",
      "lastProcessedActivityId",
      "requestedAfterEpoch",
      "resultJson",
      "queuedAt",
      "startedAt",
      "endedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    name: "SyncCursor",
    model: "syncCursor",
    orderBy: { createdAt: "asc" },
    dateTimeColumns: ["createdAt", "updatedAt"],
    columns: ["id", "appUserId", "cursorName", "cursorValue", "createdAt", "updatedAt"],
  },
];

export function createSelect(columns) {
  return Object.fromEntries(columns.map((column) => [column, true]));
}

export function getTableDefinition(tableName) {
  return TABLES.find((table) => table.name === tableName) || null;
}
