-- CreateTable
CREATE TABLE "Activity" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "athleteId" TEXT NOT NULL,
    "stravaActivityId" TEXT NOT NULL,
    "resourceState" INTEGER,
    "externalId" TEXT,
    "uploadId" TEXT,
    "name" TEXT,
    "description" TEXT,
    "type" TEXT,
    "sportType" TEXT,
    "workoutType" INTEGER,
    "startDate" DATETIME,
    "startDateLocal" DATETIME,
    "timezone" TEXT,
    "utcOffset" REAL,
    "distance" REAL,
    "movingTime" INTEGER,
    "elapsedTime" INTEGER,
    "totalElevationGain" REAL,
    "startLatlngJson" TEXT,
    "endLatlngJson" TEXT,
    "achievementCount" INTEGER,
    "kudosCount" INTEGER,
    "commentCount" INTEGER,
    "athleteCount" INTEGER,
    "photoCount" INTEGER,
    "prCount" INTEGER,
    "totalPhotoCount" INTEGER,
    "trainer" BOOLEAN,
    "commute" BOOLEAN,
    "manual" BOOLEAN,
    "private" BOOLEAN,
    "flagged" BOOLEAN,
    "averageSpeed" REAL,
    "maxSpeed" REAL,
    "averageCadence" REAL,
    "averageWatts" REAL,
    "weightedAverageWatts" INTEGER,
    "kilojoules" REAL,
    "deviceWatts" BOOLEAN,
    "hasHeartrate" BOOLEAN,
    "averageHeartrate" REAL,
    "maxHeartrate" REAL,
    "averageTemp" INTEGER,
    "sufferScore" INTEGER,
    "calories" REAL,
    "mapId" TEXT,
    "mapSummaryPolyline" TEXT,
    "mapPolyline" TEXT,
    "gearId" TEXT,
    "rawJson" TEXT,
    "summaryJson" TEXT,
    "lastFetchedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Activity_athleteId_fkey" FOREIGN KEY ("athleteId") REFERENCES "Athlete" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Activity_stravaActivityId_key" ON "Activity"("stravaActivityId");

-- CreateIndex
CREATE INDEX "Activity_athleteId_startDate_idx" ON "Activity"("athleteId", "startDate");
